export const language = {
  english: [
    "English",
    "Spanish",
    "French",
    "German",
    "Japanese",
    "Italian",
    "Korean",
    "Arab",
    "Chinese",
    "Portuguese",
    "Russian",
    "Polish",
    "Turkish",
    "Ukrainian",
    "Dutch",
    "Swedish",
    "Greek",
    "Hebrew",
    "Hungarian",
    "Hindi",
    "Czech",
    "Norwegian",
    "Georgian",
    "Armenian",
    "Finnish",
    "Serbian",
    "Tagalog",
    "Romanian",
    "Irish",
    "Icelandic",
    "Persian(Farsi)",
    "Croatian",
    "Catalan",
    "Bulgarian",
    "Bengal",
    "Latin",
    "Punjabi",
    "Thai",
    "Khmer",
    "Belorussian",
    "Urdu",
    "Gesture",
    "Sanscript",
    "Tibetan",
    "Danish",
    "Lithuanian",
    "Slovak",
    "Vietnamese",
    "Telugu",
    "Tamil",
    "Indonesian",
  ],
  russian: [
    "Английский",
    "Испанский",
    "Французский",
    "Немецкий",
    "Японский",
    "Итальянский",
    "Корейский",
    "Арабский",
    "Китайский",
    "Португальский",
    "Русский",
    "Польский",
    "Турецкий",
    "Украинский",
    "Голландский",
    "Шведский",
    "Греческий",
    "Иврит",
    "Венгерский",
    "Хинди",
    "Чешский",
    "Норвежский",
    "Грузинский",
    "Армянский",
    "Финский",
    "Сербский",
    "Тагальский",
    "Румынский",
    "Ирландский",
    "Исландский",
    "Персидский (фарси)",
    "Хорватский ",
    "Каталонский",
    "Болгарский",
    "Бенгальский",
    "Латынь",
    "Панджаби",
    "Тайский ",
    "Кхмерский",
    "Белорусский",
    "Урду",
    "Жестовый",
    "Санскрипт",
    "Тибетский ",
    "Датский",
    "Литовский",
    "Словацкий",
    "Вьетнамский",
    "Телугу",
    "Тамильский ",
    "Индонезийский",
  ],
};

export const languageInCases = {
  english: [
    "English",
    "Spanish",
    "French",
    "German",
    "Japanese",
    "Italian",
    "Korean",
    "Arab",
    "Chinese",
    "Portuguese",
    "Russian",
    "Polish",
    "Turkish",
    "Ukrainian",
    "Dutch",
    "Swedish",
    "Greek",
    "Hebrew",
    "Hungarian",
    "Hindi",
    "Czech",
    "Norwegian",
    "Georgian",
    "Armenian",
    "Finnish",
    "Serbian",
    "Tagalog",
    "Romanian",
    "Irish",
    "Icelandic",
    "Persian(Farsi)",
    "Croatian",
    "Catalan",
    "Bulgarian",
    "Bengal",
    "Latin",
    "Punjabi",
    "Thai",
    "Khmer",
    "Belorussian",
    "Urdu",
    "Gesture",
    "Sanscript",
    "Tibetan",
    "Danish",
    "Lithuanian",
    "Slovak",
    "Vietnamese",
    "Telugu",
    "Tamil",
    "Indonesian",
  ],
  russian: [
    "английского",
    "испанского",
    "французского",
    "немецкого",
    "японского",
    "итальянского",
    "корейского",
    "арабского",
    "китайского",
    "португальского",
    "русского",
    "польского",
    "турецкого",
    "украинского",
    "голландского",
    "шведского",
    "греческого",
    "иврита",
    "венгерского",
    "хинди",
    "чешского",
    "норвежского",
    "грузинского",
    "армянского",
    "финского",
    "сербского",
    "тагальского",
    "румынского",
    "ирландского",
    "исландского",
    "персидского (фарси)",
    "чорватского ",
    "каталонского",
    "болгарского",
    "бенгальского",
    "Латыни",
    "панджаби",
    "тайского",
    "кхмерского",
    "белорусского",
    "урду",
    "жестового",
    "санскрипт",
    "тибетского",
    "датского",
    "литовского",
    "словацкого",
    "вьетнамского",
    "телугу",
    "тамильского ",
    "индонезийского",
  ],
};

export const level = {
  russian: [
    "A0 - Стартовый",
    "A1 - Начальный",
    "A2 - Ниже среднего",
    "B1 - Средний",
    "B2 - Выше среднего",
    "C1 - Продвинутый",
    "C2 - Профессиональный",
  ],
  english: [
    "A0 - Starter",
    "A1 - Beginner",
    "A2 - Pre-Intermediate",
    "B1 - Intermediate",
    "B2 - Upper-Intermediate",
    "C1 - Advanced",
    "C2 - Proficiency",
  ],
};
