export const listOfCountries = [
  {
    id: 1,
    englishLabel: "Australia",
    russianLabel: "Австралия ",
  },
  { id: 2, englishLabel: "Austria", russianLabel: "Австрия" },
  {
    id: 3,
    englishLabel: "Azerbaijan",
    russianLabel: "Азербайджан",
  },
  { id: 4, englishLabel: "Albania", russianLabel: "Албания" },
  { id: 5, englishLabel: "Algeria", russianLabel: "Алжир" },
  { id: 6, englishLabel: "Anguilla", russianLabel: "Ангилья" },
  { id: 7, englishLabel: "Angola", russianLabel: "Ангола" },
  { id: 8, englishLabel: "Andorra", russianLabel: "Андорра" },
  {
    id: 9,
    englishLabel: "Antarctica",
    russianLabel: "Антарктида",
  },
  {
    id: 10,
    englishLabel: "Antigua & Barbuda",
    russianLabel: "Антигуа и Барбуда",
  },
  {
    id: 11,
    englishLabel: "Argentina",
    russianLabel: "Аргентина ",
  },
  { id: 12, englishLabel: "Armenia", russianLabel: "Армения" },
  { id: 13, englishLabel: "Aruba", russianLabel: "Аруба" },
  {
    id: 14,
    englishLabel: "Afghanistan",
    russianLabel: "Афганистан",
  },
  {
    id: 15,
    englishLabel: "American Samoa",
    russianLabel: "Американское Самоа",
  },
  {
    id: 16,
    englishLabel: "Bahamas",
    russianLabel: "Багамские о-ва",
  },
  {
    id: 17,
    englishLabel: "Bangladesh",
    russianLabel: "Бангладеш",
  },
  {
    id: 18,
    englishLabel: "Barbados",
    russianLabel: "Барбадос",
  },
  { id: 19, englishLabel: "Bahrain", russianLabel: "Бахрейн" },
  {
    id: 20,
    englishLabel: "Belarus",
    russianLabel: "Беларусь",
  },
  { id: 21, englishLabel: "Belize", russianLabel: "Белиз" },
  { id: 22, englishLabel: "Belgium", russianLabel: "Бельгия" },
  { id: 23, englishLabel: "Benin", russianLabel: "Бенин" },
  {
    id: 24,
    englishLabel: "Bermuda",
    russianLabel: "Бермудские о-ва",
  },
  {
    id: 25,
    englishLabel: "Bulgaria",
    russianLabel: "Болгария",
  },
  { id: 26, englishLabel: "Bolivia", russianLabel: "Боливия" },
  {
    id: 27,
    englishLabel: "Bonaire, Sint Eustatius & Saba",
    russianLabel: "Бонайре, Синт-Эстатиус и Саба",
  },
  {
    id: 28,
    englishLabel: "Bosnia and Herzegovina",
    russianLabel: "Босния и Герцеговина",
  },
  {
    id: 29,
    englishLabel: "Botswana",
    russianLabel: "Ботсвана",
  },
  { id: 30, englishLabel: "Brazil", russianLabel: "Бразилия" },
  { id: 31, englishLabel: "Brunei", russianLabel: "Бруней" },
  {
    id: 32,
    englishLabel: "Burkina Faso",
    russianLabel: "Буркина-Фасо",
  },
  {
    id: 33,
    englishLabel: "Burundi ",
    russianLabel: "Бурунди ",
  },
  { id: 34, englishLabel: "Butane", russianLabel: "Бутан" },
  { id: 35, englishLabel: "Vanuatu", russianLabel: "Вануату" },
  { id: 36, englishLabel: "Hungary", russianLabel: "Венгрия" },
  {
    id: 37,
    englishLabel: "Venezuela",
    russianLabel: "Венесуэла",
  },
  {
    id: 38,
    englishLabel: "UK",
    russianLabel: "Великобритания",
  },
  {
    id: 39,
    englishLabel: "Virgin Is.",
    russianLabel: "Виргинские о-ва",
  },
  { id: 40, englishLabel: "Vietnam", russianLabel: "Вьетнам" },
  { id: 41, englishLabel: "Gabon", russianLabel: "Габон" },
  { id: 42, englishLabel: "Haiti", russianLabel: "Гаити" },
  { id: 43, englishLabel: "Guyana", russianLabel: "Гайана" },
  { id: 44, englishLabel: "Gambia", russianLabel: "Гамбия" },
  { id: 45, englishLabel: "Ghana", russianLabel: "Гана" },
  {
    id: 46,
    englishLabel: "Guadeloupe",
    russianLabel: "Гваделупа",
  },
  {
    id: 47,
    englishLabel: "Guatemala",
    russianLabel: "Гватемала",
  },
  { id: 48, englishLabel: "Guinea", russianLabel: "Гвинея" },
  {
    id: 49,
    englishLabel: "Guinea-Bissau",
    russianLabel: "Гвинея-Бисау",
  },
  { id: 50, englishLabel: "Guernsey", russianLabel: "Гернси" },
  {
    id: 51,
    englishLabel: "Germany",
    russianLabel: "Германия",
  },
  {
    id: 52,
    englishLabel: "Gibraltar",
    russianLabel: "Гибралтар",
  },
  {
    id: 53,
    englishLabel: "Honduras ",
    russianLabel: "Гондурас",
  },
  {
    id: 54,
    englishLabel: "Hong Kong",
    russianLabel: "Гонконг",
  },
  {
    id: 55,
    englishLabel: "Grenada ",
    russianLabel: "Гренада",
  },
  {
    id: 56,
    englishLabel: "Greenland",
    russianLabel: "Гренландия",
  },
  { id: 57, englishLabel: "Greece", russianLabel: "Греция" },
  { id: 58, englishLabel: "Georgia", russianLabel: "Грузия" },
  { id: 59, englishLabel: "Guam", russianLabel: "Гуам" },
  { id: 60, englishLabel: "Denmark", russianLabel: "Дания" },
  {
    id: 61,
    englishLabel: "Djibouti",
    russianLabel: "Джибути",
  },
  {
    id: 62,
    englishLabel: "Dominica",
    russianLabel: "Доминика",
  },
  {
    id: 63,
    englishLabel: "Dominican Republic",
    russianLabel: "Доминиканская Республика",
  },
  { id: 64, englishLabel: "Egypt", russianLabel: "Египет" },
  { id: 65, englishLabel: "Zambia", russianLabel: "Замбия" },
  {
    id: 66,
    englishLabel: "West Sahar",
    russianLabel: "Западная Сахара",
  },
  {
    id: 67,
    englishLabel: "Zimbabwe",
    russianLabel: "Зимбабве",
  },
  { id: 68, englishLabel: "Israel", russianLabel: "Израиль" },
  { id: 69, englishLabel: "India", russianLabel: "Индия" },
  {
    id: 70,
    englishLabel: "Indonesia",
    russianLabel: "Индонезия",
  },
  { id: 71, englishLabel: "Jordan", russianLabel: "Иордания" },
  { id: 72, englishLabel: "Iraq", russianLabel: "Ирак" },
  {
    id: 73,
    englishLabel: "Ireland",
    russianLabel: "Ирландия",
  },
  {
    id: 74,
    englishLabel: "Iceland",
    russianLabel: "Исландия",
  },
  { id: 75, englishLabel: "Spain", russianLabel: "Испания" },
  { id: 76, englishLabel: "Italy", russianLabel: "Италия" },
  { id: 77, englishLabel: "Yemen", russianLabel: "Йемен" },
  {
    id: 78,
    englishLabel: "Cape Verde",
    russianLabel: "Кабо-Верде",
  },
  { id: 79, englishLabel: "Canada", russianLabel: "Канада" },
  {
    id: 80,
    englishLabel: "Kazakhstan",
    russianLabel: "Казахстан",
  },
  {
    id: 81,
    englishLabel: "Cayman Is.",
    russianLabel: "Каймановы о-ва",
  },
  {
    id: 82,
    englishLabel: "Cambodia",
    russianLabel: "Камбоджа",
  },
  {
    id: 83,
    englishLabel: "Cameroon",
    russianLabel: "Камерун",
  },
  { id: 84, englishLabel: "Qatar", russianLabel: "Катар" },
  { id: 85, englishLabel: "Kenya", russianLabel: "Кения" },
  { id: 86, englishLabel: "Cyprus", russianLabel: "Кипр" },
  {
    id: 87,
    englishLabel: "Kyrgyzstan",
    russianLabel: "Киргизия",
  },
  {
    id: 88,
    englishLabel: "Kiribati",
    russianLabel: "Кирибати",
  },
  { id: 89, englishLabel: "China", russianLabel: "Китай" },
  {
    id: 90,
    englishLabel: "Cocos (Keeling) Is.",
    russianLabel: "Кокосовые(Килинг) о-ва",
  },
  {
    id: 91,
    englishLabel: "Colombia",
    russianLabel: "Колумбия",
  },
  {
    id: 92,
    englishLabel: "Comoros Is.",
    russianLabel: "Коморские о-ва",
  },
  { id: 93, englishLabel: "Congo", russianLabel: "Конго" },
  {
    id: 94,
    englishLabel: "Democratic Republic of the Congo",
    russianLabel: "Конго (Демократическая республика)",
  },
  { id: 95, englishLabel: "Kosovo", russianLabel: "Косово" },
  {
    id: 96,
    englishLabel: "Costa Rica",
    russianLabel: "Коста-Рика",
  },
  {
    id: 97,
    englishLabel: "Ivory Coast",
    russianLabel: "Кот-д`Ивуар",
  },
  { id: 98, englishLabel: "Kuwait", russianLabel: "Кувейт" },
  { id: 99, englishLabel: "Curacao", russianLabel: "Кюрасао" },
  { id: 100, englishLabel: "Laos", russianLabel: "Лаос" },
  { id: 101, englishLabel: "Latvia", russianLabel: "Латвия" },
  { id: 102, englishLabel: "Lesotho", russianLabel: "Лесото" },
  {
    id: 103,
    englishLabel: "Liberia",
    russianLabel: "Либерия",
  },
  { id: 104, englishLabel: "Lebanon", russianLabel: "Ливан" },
  { id: 105, englishLabel: "Libya", russianLabel: "Ливия" },
  {
    id: 106,
    englishLabel: "Lithuania",
    russianLabel: "Литва",
  },
  {
    id: 107,
    englishLabel: "Liechtenstein",
    russianLabel: "Лихтенштейн",
  },
  {
    id: 108,
    englishLabel: "Luxembourg",
    russianLabel: "Люксембург",
  },
  {
    id: 109,
    englishLabel: "Mauritius",
    russianLabel: "Маврикий",
  },
  {
    id: 110,
    englishLabel: "Mauritania",
    russianLabel: "Мавритания",
  },
  {
    id: 111,
    englishLabel: "Madagascar",
    russianLabel: "Мадагаскар",
  },
  {
    id: 112,
    englishLabel: "Mayotte",
    russianLabel: "Майотта",
  },
  { id: 113, englishLabel: "Macau", russianLabel: "Макао" },
  { id: 114, englishLabel: "Malawi", russianLabel: "Малави" },
  {
    id: 115,
    englishLabel: "Malaysia",
    russianLabel: "Малайзия",
  },
  { id: 116, englishLabel: "Mali", russianLabel: "Мали" },
  {
    id: 117,
    englishLabel: "Maldives",
    russianLabel: "Мальдивы",
  },
  { id: 118, englishLabel: "Malta", russianLabel: "Мальта" },
  {
    id: 119,
    englishLabel: "Morocco",
    russianLabel: "Марокко",
  },
  {
    id: 120,
    englishLabel: "Martinique",
    russianLabel: "Мартиника",
  },
  {
    id: 121,
    englishLabel: "Marshall Is.",
    russianLabel: "Маршалловы о-ва",
  },
  { id: 122, englishLabel: "Mexico", russianLabel: "Мексика" },
  {
    id: 123,
    englishLabel: "Micronesia",
    russianLabel: "Микронезия",
  },
  {
    id: 124,
    englishLabel: "Mozambique",
    russianLabel: "Мозамбик",
  },
  {
    id: 125,
    englishLabel: "Moldova",
    russianLabel: "Молдавия",
  },
  { id: 126, englishLabel: "Monaco", russianLabel: "Монако" },
  {
    id: 127,
    englishLabel: "Mongolia",
    russianLabel: "Монголия",
  },
  {
    id: 128,
    englishLabel: "Montserrat",
    russianLabel: "Монтсеррат",
  },
  { id: 129, englishLabel: "Myanmar", russianLabel: "Мьянма" },
  {
    id: 130,
    englishLabel: "Namibia",
    russianLabel: "Намибия",
  },
  { id: 131, englishLabel: "Nauru", russianLabel: "Науру" },
  { id: 132, englishLabel: "Nepal", russianLabel: "Непал" },
  { id: 133, englishLabel: "Niger", russianLabel: "Нигер" },
  {
    id: 134,
    englishLabel: "Nigeria",
    russianLabel: "Нигерия",
  },
  {
    id: 135,
    englishLabel: "Netherlands",
    russianLabel: "Нидерланды",
  },
  {
    id: 136,
    englishLabel: "Nicaragua",
    russianLabel: "Никарагуа",
  },
  { id: 137, englishLabel: "Niue", russianLabel: "Ниуэ" },
  {
    id: 138,
    englishLabel: "New Zealand",
    russianLabel: "Новая Зеландия",
  },
  {
    id: 139,
    englishLabel: "New Caledonia",
    russianLabel: "Новая Каледония",
  },
  {
    id: 140,
    englishLabel: "Norway",
    russianLabel: "Норвегия",
  },
  {
    id: 141,
    englishLabel: "United Arab Emirates",
    russianLabel: "Объединенные Арабские Эмираты",
  },
  { id: 142, englishLabel: "Oman", russianLabel: "Оман" },
  {
    id: 143,
    englishLabel: "Pakistan",
    russianLabel: "Пакистан",
  },
  { id: 144, englishLabel: "Palau", russianLabel: "Палау" },
  {
    id: 145,
    englishLabel: "Palestine",
    russianLabel: "Палестина",
  },
  { id: 146, englishLabel: "Panama", russianLabel: "Панама" },
  {
    id: 147,
    englishLabel: "Papua New Guinea",
    russianLabel: "Папуа-Новая Гвинея",
  },
  {
    id: 148,
    englishLabel: "Paraguay",
    russianLabel: "Парагвай",
  },
  { id: 149, englishLabel: "Peru", russianLabel: "Перу" },
  { id: 150, englishLabel: "Poland", russianLabel: "Польша" },
  {
    id: 151,
    englishLabel: "Portugal",
    russianLabel: "Португалия",
  },
  {
    id: 152,
    englishLabel: "Puerto Rico",
    russianLabel: "Пуэрто-Рико",
  },
  {
    id: 153,
    englishLabel: "Reunion",
    russianLabel: "Реюньон",
  },
  { id: 154, englishLabel: "Russia", russianLabel: "Россия" },
  { id: 155, englishLabel: "Rwanda", russianLabel: "Руанда" },
  {
    id: 156,
    englishLabel: "Romania",
    russianLabel: "Румыния",
  },
  {
    id: 157,
    englishLabel: "Salvador",
    russianLabel: "Сальвадор",
  },
  { id: 158, englishLabel: "Samoa", russianLabel: "Самоа" },
  {
    id: 159,
    englishLabel: "San Marino",
    russianLabel: "Сан-Марино",
  },
  {
    id: 160,
    englishLabel: "Sao Tome & Principe",
    russianLabel: "Сан-Томе и Принсипи",
  },
  {
    id: 161,
    englishLabel: "Saudi Arabia",
    russianLabel: "Саудовская Аравия",
  },
  {
    id: 162,
    englishLabel: "Is. of St martin",
    russianLabel: "о. Святого Мартина",
  },
  {
    id: 163,
    englishLabel: "Is. of St Helena",
    russianLabel: "о. Святой Елены",
  },
  {
    id: 164,
    englishLabel: "North Macedonia",
    russianLabel: "Северная Македония",
  },
  {
    id: 165,
    englishLabel: "Northern Mariana Is.",
    russianLabel: "Северные Марианские о-ва",
  },
  {
    id: 166,
    englishLabel: "Seychelles Is.",
    russianLabel: "Сейшельские о-ва",
  },
  {
    id: 167,
    englishLabel: "Senegal",
    russianLabel: "Сенегал",
  },
  {
    id: 168,
    englishLabel: "Saint Vincent & the Grenadines",
    russianLabel: "Сент-Винсент и Гренадины",
  },
  {
    id: 169,
    englishLabel: "Saint Kitts & Nevis",
    russianLabel: "Сент-Китс и Невис",
  },
  {
    id: 170,
    englishLabel: "Saint Lucia",
    russianLabel: "Сент-Люсия",
  },
  { id: 171, englishLabel: "Serbia", russianLabel: "Сербия" },
  {
    id: 172,
    englishLabel: "Singapore",
    russianLabel: "Сингапур",
  },
  {
    id: 173,
    englishLabel: "Slovakia",
    russianLabel: "Словакия",
  },
  {
    id: 174,
    englishLabel: "Slovenia",
    russianLabel: "Словения",
  },
  {
    id: 175,
    englishLabel: "Solomon Is.",
    russianLabel: "Соломоновы о-ва",
  },
  { id: 176, englishLabel: "Somalia", russianLabel: "Сомали" },
  {
    id: 177,
    englishLabel: "Suriname",
    russianLabel: "Суринам",
  },
  {
    id: 178,
    englishLabel: "Sierra Leone",
    russianLabel: "Сьерра-Леоне",
  },
  { id: 179, englishLabel: "USA", russianLabel: "США" },
  {
    id: 180,
    englishLabel: "Tajikistan",
    russianLabel: "Таджикистан",
  },
  {
    id: 181,
    englishLabel: "Thailand",
    russianLabel: "Таиланд",
  },
  { id: 182, englishLabel: "Taiwan", russianLabel: "Тайвань" },
  {
    id: 183,
    englishLabel: "Tanzania",
    russianLabel: "Танзания",
  },
  {
    id: 184,
    englishLabel: "Timor Leste",
    russianLabel: "Тимор-Лесте",
  },
  { id: 185, englishLabel: "Togo", russianLabel: "Того" },
  {
    id: 186,
    englishLabel: "Tokelau",
    russianLabel: "Токелау",
  },
  { id: 187, englishLabel: "Tonga", russianLabel: "Тонга" },
  {
    id: 188,
    englishLabel: "Trinidad & Tobago",
    russianLabel: "Тринидад и Тобаго",
  },
  { id: 189, englishLabel: "Tuvalu", russianLabel: "Тувалу" },
  { id: 190, englishLabel: "Tunisia", russianLabel: "Тунис" },
  {
    id: 191,
    englishLabel: "Turkmenistan",
    russianLabel: "Туркменистан",
  },
  { id: 192, englishLabel: "Turkey", russianLabel: "Турция" },
  { id: 193, englishLabel: "Uganda", russianLabel: "Уганда" },
  {
    id: 194,
    englishLabel: "Uzbekistan",
    russianLabel: "Узбекистан",
  },
  {
    id: 195,
    englishLabel: "Ukraine",
    russianLabel: "Украина",
  },
  {
    id: 196,
    englishLabel: "Uruguay",
    russianLabel: "Уругвай",
  },
  {
    id: 197,
    englishLabel: "Faroe Is.",
    russianLabel: "Фарерские о-ва",
  },
  {
    id: 198,
    englishLabel: "Is. Fiji",
    russianLabel: "о. Фиджи",
  },
  {
    id: 199,
    englishLabel: "Philippines",
    russianLabel: "Филипины",
  },
  {
    id: 200,
    englishLabel: "Finland",
    russianLabel: "Финляндия",
  },
  {
    id: 201,
    englishLabel: "Falkland Is.",
    russianLabel: "Фолклендские о-ва",
  },
  { id: 202, englishLabel: "France", russianLabel: "Франция" },
  {
    id: 203,
    englishLabel: "French Guiana",
    russianLabel: "Французская Гвиана",
  },
  {
    id: 204,
    englishLabel: "French Polynesia",
    russianLabel: "Французская Полинезия",
  },
  {
    id: 205,
    englishLabel: "Croatia",
    russianLabel: "Хорватия",
  },
  {
    id: 206,
    englishLabel: "Central African Republic",
    russianLabel: "ЦАР",
  },
  { id: 207, englishLabel: "Chad", russianLabel: "Чад" },
  {
    id: 208,
    englishLabel: "Montenegro",
    russianLabel: "Черногория",
  },
  { id: 209, englishLabel: "Czech", russianLabel: "Чехия" },
  { id: 210, englishLabel: "Chile", russianLabel: "Чили" },
  {
    id: 211,
    englishLabel: "Switzerland",
    russianLabel: "Швейцария",
  },
  { id: 212, englishLabel: "Sweden", russianLabel: "Швеция" },
  {
    id: 213,
    englishLabel: "Svalbard & Jan Mayen",
    russianLabel: "Шпицберген и Ян-Майен",
  },
  {
    id: 214,
    englishLabel: "Sri Lanka",
    russianLabel: "Шри-Ланка",
  },
  {
    id: 215,
    englishLabel: "Ecuador",
    russianLabel: "Эквадор",
  },
  {
    id: 216,
    englishLabel: "Equatorial Guinea",
    russianLabel: "Экваториальная Гвинея",
  },
  {
    id: 217,
    englishLabel: "Eritrea",
    russianLabel: "Эритрея",
  },
  {
    id: 218,
    englishLabel: "Eswatini",
    russianLabel: "Эсватини",
  },
  {
    id: 219,
    englishLabel: "Estonia",
    russianLabel: "Эстония",
  },
  {
    id: 220,
    englishLabel: "Ethiopia",
    russianLabel: "Эфиопия",
  },
  {
    id: 221,
    englishLabel: "South Africa",
    russianLabel: "Южная Африка",
  },
  {
    id: 222,
    englishLabel: "South Georgia & the South Sandwich Is.",
    russianLabel: "Южная Георгия и Южные Сандвичевы о-ва",
  },
  {
    id: 223,
    englishLabel: "South Korea",
    russianLabel: "Южная Корея",
  },
  {
    id: 224,
    englishLabel: "South Sudan",
    russianLabel: "Южный Судан",
  },
  { id: 225, englishLabel: "Jamaica", russianLabel: "Ямайка" },
  { id: 226, englishLabel: "Japan", russianLabel: "Япония" },
];
